<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.gitee.mcolley</groupId>
        <artifactId>swak</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>swak-dubbo</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>swak framework dubbo</description>

    <properties>
        <skip_maven_deploy>false</skip_maven_deploy>
		<dubbo.version>2.7.21</dubbo.version>
		<spring.cloud.alibaba.version>2021.0.5.0</spring.cloud.alibaba.version>
	</properties>

    <dependencies>
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>${dubbo.version}</version>
			<scope>provided</scope>
		</dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>transmittable-thread-local</artifactId>
		</dependency>

		<dependency>
			<groupId>io.gitee.mcolley</groupId>
			<artifactId>swak-common</artifactId>
			<version>${project.version}</version>
		</dependency>

	</dependencies>

</project>
